<?php
/**
 * Tests for comment meta registration.
 */

/**
 * Test the wpce_source comment meta registration.
 */
class CommentMetaTest extends WP_UnitTestCase {

	/**
	 * Re-register meta before each test, since the WP test framework
	 * tears down registered meta between tests.
	 */
	public function set_up() {
		parent::set_up();
		Claudaborative_Editing::register();
	}

	/**
	 * The wpce_source comment meta should be registered.
	 */
	public function test_wpce_source_meta_is_registered() {
		$this->assertTrue(
			registered_meta_key_exists( 'comment', 'wpce_source' ),
			"Comment meta 'wpce_source' should be registered."
		);
	}

	/**
	 * The wpce_source meta should be exposed in the REST API.
	 */
	public function test_wpce_source_is_shown_in_rest() {
		$registered = get_registered_meta_keys( 'comment' );

		$this->assertArrayHasKey( 'wpce_source', $registered );
		$this->assertTrue( $registered['wpce_source']['show_in_rest'] );
	}

	/**
	 * Comments without the meta should return the default empty string.
	 */
	public function test_default_value_is_empty_string() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create();

		$this->assertSame( '', get_comment_meta( $comment_id, 'wpce_source', true ) );
	}

	/**
	 * The meta can be set and retrieved.
	 */
	public function test_meta_can_be_set_and_retrieved() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create();
		update_comment_meta( $comment_id, 'wpce_source', 'mcp' );

		$this->assertSame( 'mcp', get_comment_meta( $comment_id, 'wpce_source', true ) );
	}

	/**
	 * The sanitize callback should strip HTML tags.
	 */
	public function test_sanitize_strips_html() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create();
		update_comment_meta( $comment_id, 'wpce_source', '<script>alert("xss")</script>mcp' );

		$this->assertSame( 'mcp', get_comment_meta( $comment_id, 'wpce_source', true ) );
	}

	/**
	 * The label_mcp_notes filter should prepend attribution to MCP-sourced notes.
	 */
	public function test_label_mcp_notes_prepends_attribution() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create( [ 'comment_content' => 'Test note' ] );
		update_comment_meta( $comment_id, 'wpce_source', 'mcp' );

		$comment  = get_comment( $comment_id );
		$response = new WP_REST_Response(
			[
				'content' => [ 'rendered' => '<p>Test note</p>' ],
			]
		);
		$request  = new WP_REST_Request( 'GET', '/wp/v2/comments' );
		$request->set_param( 'type', 'note' );
		$request->set_param( 'context', 'edit' );

		/** @var WP_REST_Response $result */
		$result = Claudaborative_Editing::label_mcp_notes( $response, $comment, $request );
		$data   = $result->get_data();

		$this->assertStringStartsWith(
			'<p><em>(Note generated by Claudaborative Editing)</em></p>',
			$data['content']['rendered']
		);
		$this->assertStringContainsString( '<p>Test note</p>', $data['content']['rendered'] );
	}

	/**
	 * The filter should not modify non-MCP notes.
	 */
	public function test_label_mcp_notes_skips_non_mcp_notes() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create( [ 'comment_content' => 'Human note' ] );

		$comment  = get_comment( $comment_id );
		$response = new WP_REST_Response(
			[
				'content' => [ 'rendered' => '<p>Human note</p>' ],
			]
		);
		$request  = new WP_REST_Request( 'GET', '/wp/v2/comments' );
		$request->set_param( 'type', 'note' );
		$request->set_param( 'context', 'edit' );

		/** @var WP_REST_Response $result */
		$result = Claudaborative_Editing::label_mcp_notes( $response, $comment, $request );
		$data   = $result->get_data();

		$this->assertSame( '<p>Human note</p>', $data['content']['rendered'] );
	}

	/**
	 * The filter should not modify notes when context is not 'edit'.
	 */
	public function test_label_mcp_notes_skips_non_edit_context() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create();
		update_comment_meta( $comment_id, 'wpce_source', 'mcp' );

		$comment  = get_comment( $comment_id );
		$response = new WP_REST_Response(
			[
				'content' => [ 'rendered' => '<p>Note</p>' ],
			]
		);
		$request  = new WP_REST_Request( 'GET', '/wp/v2/comments' );
		$request->set_param( 'type', 'note' );
		$request->set_param( 'context', 'view' );

		/** @var WP_REST_Response $result */
		$result = Claudaborative_Editing::label_mcp_notes( $response, $comment, $request );
		$data   = $result->get_data();

		$this->assertSame( '<p>Note</p>', $data['content']['rendered'] );
	}

	/**
	 * The filter should not modify comments that are not notes.
	 */
	public function test_label_mcp_notes_skips_non_note_type() {
		/** @var int $comment_id */
		$comment_id = self::factory()->comment->create();
		update_comment_meta( $comment_id, 'wpce_source', 'mcp' );

		$comment  = get_comment( $comment_id );
		$response = new WP_REST_Response(
			[
				'content' => [ 'rendered' => '<p>Comment</p>' ],
			]
		);
		$request  = new WP_REST_Request( 'GET', '/wp/v2/comments' );
		$request->set_param( 'context', 'edit' );

		/** @var WP_REST_Response $result */
		$result = Claudaborative_Editing::label_mcp_notes( $response, $comment, $request );
		$data   = $result->get_data();

		$this->assertSame( '<p>Comment</p>', $data['content']['rendered'] );
	}
}
