<?php
/**
 * Command definitions — auto-generated from shared/commands.ts.
 *
 * Do not edit this file directly. Run from repo root: npm run generate:defs
 *
 * @package Claudaborative_Editing
 *
 * @generated
 */

namespace Claudaborative_Editing;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Shared command definitions for the WordPress plugin.
 */
class Command_Defs {

	/**
	 * Allowed prompt values for command creation.
	 *
	 * @var string[]
	 */
	const ALLOWED_PROMPTS = [
		'open-post',
		'proofread',
		'review',
		'respond-to-notes',
		'respond-to-note',
		'edit',
		'translate',
		'pre-publish-check',
		'compose',
	];

	/**
	 * Valid status transitions: current_status => [ allowed_next_statuses ].
	 *
	 * @var array<string, string[]>
	 */
	const VALID_TRANSITIONS = [
		'pending'        => [
			'running',
		],
		'running'        => [
			'completed',
			'failed',
			'awaiting_input',
		],
		'awaiting_input' => [
			'running',
			'cancelled',
		],
	];

	/**
	 * Signal command prompts — internal lifecycle signals that can
	 * transition directly from pending to completed.
	 *
	 * @var string[]
	 */
	const SIGNAL_PROMPTS = [
		'open-post',
	];

	/**
	 * Terminal command statuses.
	 *
	 * @var string[]
	 */
	const TERMINAL_STATUSES = [
		'completed',
		'failed',
		'cancelled',
		'expired',
	];
}
