<?php
/**
 * Command definitions — auto-generated from shared/commands.ts.
 *
 * Do not edit this file directly. Run from repo root: npm run generate:defs
 *
 * @generated
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Shared command definitions for the WordPress plugin.
 */
class Command_Defs {

	/**
	 * Allowed prompt values for command creation.
	 *
	 * @var string[]
	 */
	const ALLOWED_PROMPTS = [
		'proofread',
		'review',
		'respond-to-notes',
		'respond-to-note',
		'edit',
		'translate',
	];

	/**
	 * Valid status transitions: current_status => [ allowed_next_statuses ].
	 *
	 * @var array<string, string[]>
	 */
	const VALID_TRANSITIONS = [
		'pending' => [
			'running',
		],
		'running' => [
			'completed',
			'failed',
		],
	];

	/**
	 * Terminal command statuses.
	 *
	 * @var string[]
	 */
	const TERMINAL_STATUSES = [
		'completed',
		'failed',
		'cancelled',
		'expired',
	];
}
